#!/usr/bin/perl
use v5.36.0;

use Getopt::Long::Descriptive;
use JSON::XS;
use Path::Tiny;
use Process::Status;
use Term::ANSIColor;
use Time::HiRes qw(time);

$|++;

my ($opt, $usage) = describe_options(
  '%c %o PLANFILE',
  [ 'color!',       'use color' ],
);

unless (@ARGV == 1) {
  $usage->die;
}

my $planfile = path($ARGV[0]);

unless (-r $planfile) {
  die "Can't read plan file $planfile: $!\n";
}

my $plan = eval { decode_json($planfile->slurp) };

unless ($plan) {
  die "Error decoding plan file $planfile: $@\n";
}

my $run_id = $plan->{run_id};

my sub START ($task) {
  if ($ENV{FM_TASKSTREAM}) {
    say "TASK::START::$task";
  } else {
    say "Starting task: $task...";
  }
}

my sub maybe_colored {
  state $COLOR = $opt->color;
  return $_[1] unless $COLOR;
  return colored($_[0], $_[1]);
}

my sub rem {
  printf "[%s] %s\n", maybe_colored(['bright_magenta'], 'VIRT'), $_[0];
}

package TestProcess;
use Moo;

has run_id => (is => 'ro', required => 1);
has root   => (is => 'ro', required => 1);

has run_data => (
  is => 'ro',
  init_arg => undef,
  default  => sub {  {}  },
);

has event_log => (
  is => 'ro',
  init_arg => undef,
  default  => sub {  []  },
);

sub log_event ($self, $event) {
  push $self->event_log->@*, $event;
  return;
}

sub run_cmd ($self, $cmd, $desc = $cmd, $arg = undef) {
  my $may_fail = $arg && $arg->{may_fail};

  rem "Running command: $cmd";

  my $start = time;
  system('bash', '-c', $cmd);
  my $ps = Process::Status->new;

  my $end  = time;
  my $time = $end - $start;

  $self->log_event({
    slug    => $desc || $cmd,
    command => $cmd,
    took    => 0 + sprintf('%.2f', $time),
    result  => Process::Status->as_struct,
  });

  unless ($arg->{may_fail}) {
    Process::Status->assert_ok($cmd);
  }

  return $ps->exitstatus;
}

sub STEP_boot_up ($self) {
  my $user = `whoami`;
  START("initializing testrunner, running as $user");

  my $root = $self->root;

  mkdir $root
    or die "can't create test run directory $root: $!";

  my $hm_head = `cd /home/mod_perl/hm; git rev-parse HEAD`;
  chomp $hm_head;
  $self->run_data->{hm_head} = $hm_head;

  my $box_version = `cat /etc/fminabox.version`;
  chomp $box_version;
  $self->run_data->{box_version} = $box_version;

  return;
}

sub STEP_start_early_services ($self) {
  START("starting early services");

  $self->run_cmd("sudo /etc/init.d/rsyslog start", "start rsyslog");
  $self->run_cmd("sudo /etc/init.d/consul start",  "start consul");

  return;
}

sub STEP_setup_cyrus ($self) {
  # if ($opt->cyrus_version) {
  #   return $self->STEP_install_cyrus;
  # }

  START("checking Cyrus version");
  my $cyrus_version = `fmcyrpkg versions | grep fm | head -n1 | awk '{printf \$2}'`;
  chomp $cyrus_version;

  $self->run_data->{cyrus_version} = $cyrus_version;
  return;
}

sub STEP_install_cyrus ($self) {
  my $cyrus_version = die "!!!"; # $opt->cyrus_version;
  START("installing Cyrus $cyrus_version");

  $self->run_data->{cyrus_version} = $cyrus_version;

  my $root = $self->root;
  $self->run_cmd(
    "sudo fmcyrpkg deploy --really --yolo --allow-downgrade --type stable $cyrus_version 2>&1 | tee $root/deploy-cyrus.log",
    "fmcyrpkg deploy",
  );
}

sub STEP_debian_upgrade ($self) {
  START("running Debian upgrade");

  my $root = $self->root;
  $self->run_cmd(
    "sudo /home/mod_perl/hm/scripts/debian_upgrade.sh --really 2>&1 | tee $root/debup.log",
    "debian_upgrade.sh",
  );
}

sub STEP_start_services ($self) {
  # First up, get service running.  Without this, there's nothing to test.
  # This is optional because if we're running it against an existing, running
  # box, or just doing a compile test. -- adavis, 2021-03-01
  START("starting all services");

  my $root = $self->root;
  $self->run_cmd(
    "sudo /home/mod_perl/hm/utils/Services.pl all start -v 2>&1 | tee $root/srv-all-start.log",
    "srv all start",
  );
}

sub STEP_stop_services ($self) {
  START("stopping services");

  my $root = $self->root;
  $self->run_cmd(
    "sudo /home/mod_perl/hm/utils/Services.pl all fstop -v 2>&1 | tee $root/srv-all-stop.log",
    "srv all fstop",
    { may_fail => 1 },
  );
}

# The arguments here match the GitLab CI variables:
#   $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH - like "fastmail/hm" or "rjbs/hm"
#   $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME  - like "master" or "bak-1234-pie"
sub STEP_switch_to_branch ($self, $project_path, $branch) {
  START("switching to branch $branch on project $project_path");
  chdir("/home/mod_perl/hm") or die "can't chdir to hm!";

  my $remote;

  if ($project_path eq 'fastmail/hm') {
    $remote = 'fastmail';
  } else {
    rem "Setting up remote...";

    $remote = $project_path =~ s{/}{-}gr;
    $self->run_cmd(
      "git remote add $remote git\@gitlab.fm:$project_path.git",
      "adding remote $remote",
    );
  }

  $self->run_cmd("git fetch $remote");

  rem "Resetting hard to $remote/$branch";
  $self->run_cmd("git reset --quiet --hard $remote/$branch");
  return;
}

sub STEP_db_update ($self) {
  START("updating database to latest");

  my $root = $self->root;
  $self->run_cmd(
    "/home/mod_perl/hm/db/dbupdate.pl --version 0 /home/mod_perl/hm/db/fm.sql --force 2>&1 | tee $root/dbupdate.log",
    "dbudpate.pl",
  );
}

sub STEP_knot_update ($self) {
  START("checking for knot diff");

  my $root = $self->root;
  my $exitstatus = $self->run_cmd(
    "/home/mod_perl/hm/bin/humans/fmknot diffourdomains --all 2>&1 | tee $root/knot-diff.log",
    "knot diff",
    { may_fail => 1 },
  );

  return if $exitstatus == 0;

  if ($exitstatus > 1) {
    die "knot diff failed, exited $exitstatus";
  }

  START("updating our domains in knot");
  $self->run_cmd(
    "(/home/mod_perl/hm/bin/robots/knot-update-our-domains --all --really; /home/mod_perl/hm/bin/humans/fmrbl rebuild; /home/mod_perl/hm/bin/robots/update_domain_common_fastmail_flag --really) 2>&1 | tee $root/knot-update.log",
    "knot update",
  );
}

sub STEP_cyrus_tmpfs ($self) {
  START("configuring Cyrus to use tmpfs");

  my $root = $self->root;
  $self->run_cmd(
    "(source /etc/fmhome/bashrc; cd /home/mod_perl/hm; penv; fmdev tmpfs --really) 2>&1 | tee $root/fmdev-tmpfs.log",
    "fmdev tmpfs",
  );
}

sub STEP_conf_update ($self) {
  START("installing all config files");

  my $root = $self->root;
  $self->run_cmd(
    "sudo make -C conf/ installfiles REALLY=1 2>&1 | tee $root/installfiles.log",
    "conf installfiles",
  );

  return;
}

sub STEP_newt_full ($self) {
  START("running Newt");
  my $root = $self->root;

  my @tests = "t/me-util.t"; # XXX

  # Test slow things
  my $yath_env = join(" ",
    "ME_TEST_SLOW=1",
    "AUTOMATED_TESTING=DAILY",
    "JUNIT_TEST_FILE=$root/yath-output.xml",
    "ME_LOG_TESTIDENT=yath",
    "ZENDESK_CLIENT_RATE_LIMIT_RETRY_COUNT=3"
  );

  my $yath_opts = "--tlib -P ME::Test::Instance --bzip2";

  my $cmd = join q{ ; },
    qq{source /etc/fmhome/bashrc},
    qq{penv},
    qq{cd /home/mod_perl/hm},
    qq{$yath_env yath test $yath_opts --log-file $root/test-results @tests};

  $self->run_cmd(
    "sudo bash -c '$cmd'",
    "yath",
    { may_fail => 1 },
  );
}

sub STEP_cassandane ($self) {
  START("running Cassandane");

  my $cass_args = ''; # XXX
  # my $cass_args = $opt->cass_args ? join(' ', $opt->cass_args->@*) : '';

  my $user = `whoami`;
  chomp($user);

  my $root = $self->root;

  my $cmd = join q{ && },
    qq{set -o pipefail},
    qq{set -x},
    qq{export FMADMIN=$user},
    qq{cd $root},
    qq{fmdev cass --allow-root --working-dir $root 2>&1 | tee $root/fmdev-cass.log},
    qq{cd cyrus-imapd/cassandane},
    qq{chown cyrus .},
    qq{sudo -u cyrus env PERL5LIB=/home/mod_perl/hm:\$PERL5LIB ./testrunner.pl --config $root/cassandane.ini $cass_args 2>&1 | tee $root/cassandane.log};

  $cmd = "sudo bash -c '$cmd'";

  $self->run_cmd($cmd, "cassandane", { may_fail => 1 });

  $self->run_cmd(
    "sudo cp -r $root/cyrus-imapd/cassandane/reports $root/cass_reports",
    "cp reports",
  );

  $self->run_cmd(
    "sudo tar -cJf $root/archive.tar.xz /dev/shm/cass/ 2>&1 | tee -a $root/tar.log",
    "tar",
    { may_fail => 1 },
  );

  return;
}

sub STEP_log_gather ($self) {
  START("gathering logs");

  my $root = $self->root;

  my $log_grep = '/home/mod_perl/hm/bin/humans/log-grep';

  # Search for absolutely all logs for the last day and write them out.
  my $cmd = "$log_grep -L 1d -l '*' --stream '' | gzip > $root/lg-logs.txt.gz";

  $self->run_cmd($cmd, 'lg', { may_fail => 1 });

  Path::Tiny::path("$root/events.json")->spew_utf8(
    JSON::XS->new->pretty->canonical->encode({
      $self->run_data->%*,
      events => $self->event_log,
    }),
  );
}

package main;

my $testproc = TestProcess->new({
  run_id => $run_id,
  root   => "/tmp/run-" . $run_id,
});

my @instructions = $plan->{program}->@*;

for my $instruction (@instructions) {
  my ($name, @args) = @$instruction;

  my $method = "STEP_$name";

  unless ($testproc->can($method)) {
    # XXX: validate all this before starting any work!
    die "Test runner has no implementation for $name step\n";
  }

  $testproc->$method(@args);
}

say "All done!";
